name: Metrics

on:
  # Schedule hourly update
  schedule: [{cron: "0 * * * *"}]

  workflow_dispatch:
  push: 
    branches: [main, master]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bindsdev
          template: classic
          config_timezone: America/Chicago
          base: header, activity, community, repository
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_notable: yes
          plugin_calender: yes
          plugin_languages: yes